version: '3'

services:
  my_admin_front:
    image: hub.develobeer.blog/admin-front:${TAG}

    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

    ports:
      - "8888:80"
