version: '3'

services:
  my_admin_front:
    build:
      context: .

    image: admin-front:latest

    container_name: myAdminFront

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

    ports:
      - "8888:80"
                       
